#   DEFINE SIZE OF BOARD
WIDTH = HEIGHT = 512
DIMENSION = 8
SQ_SIZE = WIDTH // DIMENSION

MAX_FPS = 15
colorBoard = [(255, 255, 255), (0, 102, 0), (255, 255, 0)]

#   DEFINE SCREEN OF PANEL
WIDTH_PANEL = WIDTH // 2
HEIGHT_PANEL = HEIGHT

#   DEFINE POSITION OF MOVE BOX
WIDTH_MOVE_BOX = WIDTH_PANEL
HEIGHT_MOVE_BOX = HEIGHT_PANEL * 5 / 8
LEFT_MOVE_BOX = 0
TOP_MOVE_BOX = 2 * SQ_SIZE

#   DEFINE SIZE OF LABEL

WIDTH_LABEL = WIDTH_PANEL
HEIGHT_LABEL = SQ_SIZE // 2

# DEFINE POSITION OF TIMER, TURN, POSSIBLE_MOVE
LEFT_TIMER = 0
TOP_TIMER = 0

LEFT_TURN = 0
TOP_TURN = SQ_SIZE // 2

LEFT_POSSIBLE_MOVE = 0
TOP_POSSIBLE_MOVE = SQ_SIZE

LEFT_INCHECK = 0
TOP_INCHECK = 3 * SQ_SIZE // 2

# DEFINE SIZE OF BUTTON


#   DEFINE SIZE OF WINDOW
WIDTH_WINDOW = WIDTH + WIDTH_PANEL
HEIGHT_WINDOW = HEIGHT
