WIDTH = HEIGHT = 512
DIMENSION = 8
SQ_SIZE = WIDTH / DIMENSION
MAX_FPS = 15
colorBoard = [(255, 255, 255), (0, 102, 0), (255, 255, 0)]

WIDTH_PANEL = WIDTH/2
HEIGHT_PANEL = HEIGHT

WIDTH_MOVE_BOX = WIDTH_PANEL
HEIGHT_MOVE_BOX = HEIGHT_PANEL*5/8

WIDTH_WINDOW = WIDTH + WIDTH_PANEL
HEIGHT_WINDOW = HEIGHT