DEPTH = 3

#   DEFINE SIZE OF BOARD
WIDTH = HEIGHT = 512
DIMENSION = 8
SQ_SIZE = WIDTH // DIMENSION

MAX_FPS = 30
colorBoard = [(255, 255, 255), (0, 102, 0), (255, 255, 0)]

#   DEFINE SCREEN OF PANEL
LEFT_PANEL = WIDTH
TOP_PANEL = 0
WIDTH_PANEL = 4 * SQ_SIZE
HEIGHT_PANEL = HEIGHT

#   DEFINE POSITION OF MOVE BOX
WIDTH_MOVE_BOX = WIDTH_PANEL - 30
HEIGHT_MOVE_BOX = HEIGHT_PANEL // 2
LEFT_MOVE_BOX = 0
TOP_MOVE_BOX = 2 * SQ_SIZE

#   DEFINE SIZE OF LABEL

WIDTH_LABEL = WIDTH_PANEL - 30
HEIGHT_LABEL = SQ_SIZE // 2

# DEFINE SIZE OF BUTTON

WIDTH_BUTTON = SQ_SIZE
HEIGHT_BUTTON = SQ_SIZE

# DEFINE POSITION OF TIMER, TURN, POSSIBLE_MOVE
LEFT_TIMER = 0
TOP_TIMER = 0

LEFT_TURN = 0
TOP_TURN = SQ_SIZE // 2

LEFT_POSSIBLE_MOVE = 0
TOP_POSSIBLE_MOVE = SQ_SIZE

LEFT_INCHECK = 0
TOP_INCHECK = 3 * SQ_SIZE // 2

TOP_BUTTON = HEIGHT_PANEL * 3 // 4
LEFT_BUTTON1 = 15
LEFT_BUTTON2 = LEFT_BUTTON1 + SQ_SIZE
LEFT_BUTTON3 = LEFT_BUTTON2 + SQ_SIZE

#   DEFINE SIZE OF WINDOW
HEIGHT_WINDOW = HEIGHT
WIDTH_WINDOW = WIDTH + WIDTH_PANEL

# Define AI PANEL
LEFT_AI = WIDTH + WIDTH_PANEL
TOP_AI = 0
WIDTH_AI = 4 * SQ_SIZE
HEIGHT_AI = HEIGHT

# Define AI SCREEN
HEIGHT_WINDOW_AI = HEIGHT
WIDTH_WINDOW_AI = WIDTH + WIDTH_PANEL + WIDTH_AI
